"""Add relationsship

Revision ID: 1566d9b9d860
Revises: a759cbbd04af
Create Date: 2024-09-20 08:15:27.359703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # type: ignore
from sqlalchemy.dialects import mysql  # type: ignore

# revision identifiers, used by Alembic.
revision: str = "1566d9b9d860"
down_revision: Union[str, None] = "a759cbbd04af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_category_ingredient_id_category_ingredient",
        table_name="category_ingredient",
    )
    op.drop_table("category_ingredient")
    op.create_foreign_key(None, "favorities", "users", ["id_user"], ["id_user"])
    op.create_foreign_key(None, "favorities", "recipe", ["id_recipe"], ["id_recipe"])
    op.create_foreign_key(
        None,
        "ingredient",
        "nutrition_info",
        ["id_nutrition_info"],
        ["id_nutrition_info"],
    )
    op.create_foreign_key(None, "menu", "type_menu", ["id_typeMenu"], ["id_typeMenu"])
    op.create_foreign_key(None, "notification", "users", ["id_user"], ["id_user"])
    op.create_foreign_key(None, "pantry", "users", ["id_user"], ["id_user"])
    op.create_foreign_key(None, "pantry", "quantity", ["id_quantity"], ["id_quantity"])
    op.create_foreign_key(
        None, "pantry", "ingredient", ["id_ingredient"], ["id_ingredient"]
    )
    op.create_foreign_key(None, "posts", "users", ["id_user"], ["id_user"])
    op.create_foreign_key(None, "recipe", "users", ["id_user"], ["id_user"])
    op.create_foreign_key(None, "recipe", "quantity", ["id_quantity"], ["id_quantity"])
    op.drop_column("recipe", "id_ingredient")
    op.alter_column(
        "recipe_category", "id_category", existing_type=mysql.INTEGER(), nullable=False
    )
    op.drop_index("ix_recipe_category_id_recipe", table_name="recipe_category")
    op.create_foreign_key(
        None, "recipe_category", "recipe", ["id_recipe"], ["id_recipe"]
    )
    op.create_foreign_key(
        None, "recipe_category", "category", ["id_category"], ["id_category"]
    )
    op.alter_column(
        "recipe_menu", "id_menu", existing_type=mysql.INTEGER(), nullable=False
    )
    op.drop_index("ix_recipe_menu_id_recipe", table_name="recipe_menu")
    op.create_foreign_key(None, "recipe_menu", "recipe", ["id_recipe"], ["id_recipe"])
    op.create_foreign_key(None, "recipe_menu", "menu", ["id_menu"], ["id_menu"])
    op.create_foreign_key(None, "shopping_list", "users", ["id_user"], ["id_user"])
    op.create_foreign_key(
        None, "shopping_list", "quantity", ["id_quantity"], ["id_quantity"]
    )
    op.create_foreign_key(
        None, "shopping_list", "ingredient", ["id_ingredient"], ["id_ingredient"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "shopping_list", type_="foreignkey")
    op.drop_constraint(None, "shopping_list", type_="foreignkey")
    op.drop_constraint(None, "shopping_list", type_="foreignkey")
    op.drop_constraint(None, "recipe_menu", type_="foreignkey")
    op.drop_constraint(None, "recipe_menu", type_="foreignkey")
    op.create_index(
        "ix_recipe_menu_id_recipe", "recipe_menu", ["id_recipe"], unique=False
    )
    op.alter_column(
        "recipe_menu", "id_menu", existing_type=mysql.INTEGER(), nullable=True
    )
    op.drop_constraint(None, "recipe_category", type_="foreignkey")
    op.drop_constraint(None, "recipe_category", type_="foreignkey")
    op.create_index(
        "ix_recipe_category_id_recipe", "recipe_category", ["id_recipe"], unique=False
    )
    op.alter_column(
        "recipe_category", "id_category", existing_type=mysql.INTEGER(), nullable=True
    )
    op.add_column(
        "recipe",
        sa.Column("id_ingredient", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "recipe", type_="foreignkey")
    op.drop_constraint(None, "recipe", type_="foreignkey")
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_constraint(None, "pantry", type_="foreignkey")
    op.drop_constraint(None, "pantry", type_="foreignkey")
    op.drop_constraint(None, "pantry", type_="foreignkey")
    op.drop_constraint(None, "notification", type_="foreignkey")
    op.drop_constraint(None, "menu", type_="foreignkey")
    op.drop_constraint(None, "ingredient", type_="foreignkey")
    op.drop_constraint(None, "favorities", type_="foreignkey")
    op.drop_constraint(None, "favorities", type_="foreignkey")
    op.create_table(
        "category_ingredient",
        sa.Column(
            "id_category_ingredient",
            mysql.INTEGER(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("id_ingredient", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("id_category", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id_category_ingredient"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_category_ingredient_id_category_ingredient",
        "category_ingredient",
        ["id_category_ingredient"],
        unique=False,
    )
    # ### end Alembic commands ###
