"""Initial migration

Revision ID: a759cbbd04af
Revises: 
Create Date: 2024-10-12 11:25:48.180406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a759cbbd04af"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rol",
        sa.Column("id_rol", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id_rol"),
    )
    op.create_index(op.f("ix_rol_id_rol"), "rol", ["id_rol"], unique=False)
    op.create_index(op.f("ix_rol_name"), "rol", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rol_name"), table_name="rol")
    op.drop_index(op.f("ix_rol_id_rol"), table_name="rol")
    op.drop_table("rol")
    # ### end Alembic commands ###
