"""First Commit - Alembic

Revision ID: ad2c612a660c
Revises: 1566d9b9d860
Create Date: 2024-10-12 11:08:25.017703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad2c612a660c"
down_revision: Union[str, None] = "1566d9b9d860"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id_category", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id_category"),
    )
    op.create_index(
        op.f("ix_category_id_category"), "category", ["id_category"], unique=False
    )
    op.create_index(op.f("ix_category_name"), "category", ["name"], unique=False)
    op.create_table(
        "category_ingredient",
        sa.Column("id_category_ingredient", sa.Integer(), nullable=False),
        sa.Column("id_ingredient", sa.Integer(), nullable=True),
        sa.Column("id_category", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_category_ingredient"),
    )
    op.create_index(
        op.f("ix_category_ingredient_id_category_ingredient"),
        "category_ingredient",
        ["id_category_ingredient"],
        unique=False,
    )
    op.create_table(
        "favorities",
        sa.Column("id_favorities", sa.Integer(), nullable=False),
        sa.Column("id_recipe", sa.Integer(), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_favorities"),
    )
    op.create_index(
        op.f("ix_favorities_id_favorities"),
        "favorities",
        ["id_favorities"],
        unique=False,
    )
    op.create_table(
        "group",
        sa.Column("id_group", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id_group"),
    )
    op.create_index(op.f("ix_group_id_group"), "group", ["id_group"], unique=False)
    op.create_index(op.f("ix_group_name"), "group", ["name"], unique=False)
    op.create_table(
        "ingredient",
        sa.Column("id_ingredient", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("expiration_date", sa.String(length=50), nullable=True),
        sa.Column("id_nutrition_info", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_ingredient"),
    )
    op.create_index(
        op.f("ix_ingredient_id_ingredient"),
        "ingredient",
        ["id_ingredient"],
        unique=False,
    )
    op.create_index(op.f("ix_ingredient_name"), "ingredient", ["name"], unique=False)
    op.create_table(
        "menu",
        sa.Column("id_menu", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("id_typeMenu", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_menu"),
    )
    op.create_index(op.f("ix_menu_id_menu"), "menu", ["id_menu"], unique=False)
    op.create_index(op.f("ix_menu_name"), "menu", ["name"], unique=False)
    op.create_table(
        "notification",
        sa.Column("id_notification", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=True),
        sa.Column("content", sa.String(length=50), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_notification"),
    )
    op.create_index(
        op.f("ix_notification_id_notification"),
        "notification",
        ["id_notification"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_title"), "notification", ["title"], unique=False
    )
    op.create_table(
        "nutrition_info",
        sa.Column("id_nutrition_info", sa.Integer(), nullable=False),
        sa.Column("kcal", sa.String(length=50), nullable=True),
        sa.Column("protein", sa.String(length=50), nullable=True),
        sa.Column("fat", sa.String(length=50), nullable=True),
        sa.Column("carbs", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id_nutrition_info"),
    )
    op.create_index(
        op.f("ix_nutrition_info_id_nutrition_info"),
        "nutrition_info",
        ["id_nutrition_info"],
        unique=False,
    )
    op.create_table(
        "pantry",
        sa.Column("id_pantry", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("id_ingredient", sa.Integer(), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.Column("id_quantity", sa.Integer(), nullable=True),
        sa.Column("expiration_date", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id_pantry"),
    )
    op.create_index(op.f("ix_pantry_id_pantry"), "pantry", ["id_pantry"], unique=False)
    op.create_index(op.f("ix_pantry_name"), "pantry", ["name"], unique=False)
    op.create_table(
        "quantity",
        sa.Column("id_quantity", sa.Integer(), nullable=False),
        sa.Column("grammes", sa.String(length=50), nullable=True),
        sa.Column("liters", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id_quantity"),
    )
    op.create_index(
        op.f("ix_quantity_id_quantity"), "quantity", ["id_quantity"], unique=False
    )
    op.create_table(
        "recipe",
        sa.Column("id_recipe", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=50), nullable=True),
        sa.Column("instructions", sa.String(length=50), nullable=True),
        sa.Column("preparation_time", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("difficulty", sa.String(length=50), nullable=True),
        sa.Column("id_ingredient", sa.Integer(), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.Column("id_quantity", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_recipe"),
    )
    op.create_index(op.f("ix_recipe_id_recipe"), "recipe", ["id_recipe"], unique=False)
    op.create_index(op.f("ix_recipe_name"), "recipe", ["name"], unique=False)
    op.create_table(
        "recipe_category",
        sa.Column("id_recipe", sa.Integer(), nullable=False),
        sa.Column("id_category", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_recipe"),
    )
    op.create_index(
        op.f("ix_recipe_category_id_recipe"),
        "recipe_category",
        ["id_recipe"],
        unique=False,
    )
    op.create_table(
        "recipe_menu",
        sa.Column("id_recipe", sa.Integer(), nullable=False),
        sa.Column("id_menu", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_recipe"),
    )
    op.create_index(
        op.f("ix_recipe_menu_id_recipe"), "recipe_menu", ["id_recipe"], unique=False
    )
    op.create_table(
        "shopping_list",
        sa.Column("id_shopping_list", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("total_items", sa.String(length=50), nullable=True),
        sa.Column("creation_date", sa.String(length=50), nullable=True),
        sa.Column("id_user", sa.Integer(), nullable=True),
        sa.Column("id_quantity", sa.Integer(), nullable=True),
        sa.Column("id_ingredient", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id_shopping_list"),
    )
    op.create_index(
        op.f("ix_shopping_list_id_shopping_list"),
        "shopping_list",
        ["id_shopping_list"],
        unique=False,
    )
    op.create_table(
        "type_menu",
        sa.Column("id_typeMenu", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id_typeMenu"),
    )
    op.create_index(
        op.f("ix_type_menu_id_typeMenu"), "type_menu", ["id_typeMenu"], unique=False
    )
    op.create_index(op.f("ix_type_menu_name"), "type_menu", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_type_menu_name"), table_name="type_menu")
    op.drop_index(op.f("ix_type_menu_id_typeMenu"), table_name="type_menu")
    op.drop_table("type_menu")
    op.drop_index(op.f("ix_shopping_list_id_shopping_list"), table_name="shopping_list")
    op.drop_table("shopping_list")
    op.drop_index(op.f("ix_recipe_menu_id_recipe"), table_name="recipe_menu")
    op.drop_table("recipe_menu")
    op.drop_index(op.f("ix_recipe_category_id_recipe"), table_name="recipe_category")
    op.drop_table("recipe_category")
    op.drop_index(op.f("ix_recipe_name"), table_name="recipe")
    op.drop_index(op.f("ix_recipe_id_recipe"), table_name="recipe")
    op.drop_table("recipe")
    op.drop_index(op.f("ix_quantity_id_quantity"), table_name="quantity")
    op.drop_table("quantity")
    op.drop_index(op.f("ix_pantry_name"), table_name="pantry")
    op.drop_index(op.f("ix_pantry_id_pantry"), table_name="pantry")
    op.drop_table("pantry")
    op.drop_index(
        op.f("ix_nutrition_info_id_nutrition_info"), table_name="nutrition_info"
    )
    op.drop_table("nutrition_info")
    op.drop_index(op.f("ix_notification_title"), table_name="notification")
    op.drop_index(op.f("ix_notification_id_notification"), table_name="notification")
    op.drop_table("notification")
    op.drop_index(op.f("ix_menu_name"), table_name="menu")
    op.drop_index(op.f("ix_menu_id_menu"), table_name="menu")
    op.drop_table("menu")
    op.drop_index(op.f("ix_ingredient_name"), table_name="ingredient")
    op.drop_index(op.f("ix_ingredient_id_ingredient"), table_name="ingredient")
    op.drop_table("ingredient")
    op.drop_index(op.f("ix_group_name"), table_name="group")
    op.drop_index(op.f("ix_group_id_group"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_favorities_id_favorities"), table_name="favorities")
    op.drop_table("favorities")
    op.drop_index(
        op.f("ix_category_ingredient_id_category_ingredient"),
        table_name="category_ingredient",
    )
    op.drop_table("category_ingredient")
    op.drop_index(op.f("ix_category_name"), table_name="category")
    op.drop_index(op.f("ix_category_id_category"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
